### ISSUE TITLE
簡単なアプリの作り方を調べる

### ISSUE THREAD

**Issue by iimuz** [iimuz/issues#26]
コードを書くことができる人だとコマンドラインとかを使った方が早いです。
一方で、ソフトウェア開発では色々なバックグランドの人が集まって行うことが多いです。
そのため、GUIがあったほうが説明や簡易に使ってもらったりするのに便利です。

そこで、簡単なGUIをつける方法に関して調べて試してみようと思います。

**Comment by iimuz** [comment]
ウェブアプリだけに限らず高速性が求められることも多いのでネイティブアプリとすることも視野に入れます。

**Comment by iimuz** [comment]
goで簡単なウェブアプリを作る方法が示されていたので参考に読んでみようと思います。
シングルバイナリで複数環境に対応できるのは非常に魅力的です。

* [Big Sky: Golang と Vue.js で簡単なアプリケーションを作ってみた。](https://mattn.kaoriya.net/software/lang/go/20180330093346.htm)
* [GitHub: mattn/go-vue-example](https://github.com/mattn/go-vue-example)

**Comment by iimuz** [comment]
qtを使えば高速なネイティブアプリを単一ソースから作れそうです。

**Comment by iimuz** [comment]
mattn/go-vue-example を実行するのにgceを使ったが、port forward周りで引っかかったので覚書

環境構成は下記のようになっています。(上から順に下につながっている)

* windows 10pro(chrome)
* wsl
* docker-gcloud(hyper-v)
* gce(debian instance)
* docker-golang(mattn/go-vue-exampleをビルド及び実行)
    * go-vue-exampleに必要なmongodbもdocker-composeを利用して起動

この時、chromeからgo-vue-exampleのサーバへ接続するためには、各部分でポートフォワードが必要になります。
基本的にはlocalhostに対して開放しておけばよいのですが、docker-gcloudの部分だけ、0.0.0.0で開放しなければ動きませんでした。
ただ、dokcer-gcloudの部分ではportを特定部分をlocalhostに対して開けているだけなので、他から接続はできないはず(間違ってる??)です。

* windows 10pro(chrome): localhost:4000
* wsl: ターミナルとして利用しているだけなので何もなし
* docker-gcloud(hyper-v): gcloud instance ssh container-name -- -L 0.0.0.0:4000:localhost:4000
* gce(debian instance): dockerをport4000をlocalhostに対して開放して実行
* docker-golang(mattn/go-vue-exampleをビルド及び実行): port4000に対してサーバを待ち受ける
    * go-vue-exampleに必要なmongodbもdocker-composeを利用して起動

**Comment by iimuz** [comment]
上記はよく考えたらdockerコンテナの中を指すことになるので成功しなかった気がします。
0.0.0.0でなくても、windows側からのipを指定すれば動作する気がします。

**Comment by iimuz** [comment]
mattn/go-vue-example をdocker環境で動かすために簡易にdocker-compose.ymlを作成しました。
下記docker-compose.ymlとrun.shをリポジトリ直下において、docker-compose up -d で起動して localhost:4000 にアクセスすれば動作します。

docker-compose.yml

```yml
version: "3"
services:
  go:
    image: iimuz/golang-dev:v1.9.2-1.1.0
    restart: always
    user: root
    ports:
      - 127.0.0.1:4000:4000
    environment:
      TZ: 'Asia/Tokyo'
      MONGODB_URI: 'mongodb://root:example@mongo'
    volumes:
      - src:/go/src/github.com/mattn/go-vue-example
    command: sh /go/src/github.com/mattn/go-vue-example/run.sh

  mongo:
    image: mongo:3.7.9-jessie
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
```

run.sh

```bash
sleep 5s
cd /go/src/github.com/mattn/go-vue-example
dep init
dep ensure
go build
./go-vue-example
```
